DELETE FROM `trinity_string` WHERE `entry` IN (30000, 30001, 30002, 30003, 30004, 30005, 30006);
INSERT INTO `trinity_string`(`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `content_loc9`, `content_loc10`, `content_loc11`, `content_female`, `content_female_loc1`, `content_female_loc2`, `content_female_loc3`, `content_female_loc4`, `content_female_loc5`, `content_female_loc6`, `content_female_loc7`, `content_female_loc8`, `content_female_loc9`, `content_female_loc10`, `content_female_loc11`) VALUES 
(30000, "|cff4CFF00[SoloCraft]|r system active", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "|cff4CFF00[СолоКрафт]|r система активирована.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(30001, "|cffFF0000[SoloCraft]|r |cffFF8000 %s entered %s - Difficulty Offset: %0.2f. Spellpower Bonus: %i. Class Balance Weight: %i. XP Gain: |cffFF0000%s|cffFF8000 XP Balancing:|cffFF0000%s |cff4CFF00", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "|cffFF0000[СолоКрафт]|r |cffFF8000 Игрок %s вошел в %s - Изменение сложности: %0.2f. Бонус к силе заклинаний: %i. Балансировочное значение класса: %i. Получение опыта:|cffFF0000%s|cffFF8000 Баланс опыта:|cffFF0000%s|cffFF8000", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(30002, "|cff4CFF00[SoloCraft]|r |cffFF0000 %s entered %s - |cffFF0000You have not been buffed.|r |cffFF8000Your level is higher than the max level (%i) threshold for this dungeon.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "|cffFF0000[СолоКрафт]|r |cffFF8000 %s вошел в %s - |cffFF0000Вы не получили бафф.|r |cffFF8000Ваш уровень выше максимального уровня, (%i) порог этого подземелья.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(30003, "|cffFF0000[SoloCraft]|r |cffFF8000 %s entered %s - |cffFF0000BE ADVISED - You have been debuffed by offset: %0.2f with a Class Balance Weight: %i. |cffFF8000A group member already inside has the dungeon\'s full buff offset. No Spellpower buff will be applied to spell casters. ALL group members must exit the dungeon and re-enter to receive a balanced offset.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "|cffFF0000[СолоКрафт] |cffFF8000Игрок %s вошел в %s - |cffFF0000ПОМНИТЕ - Вы не получили дебафф по изменению сложности: %0.2f с балансировочным значением класса: %i и не будете получать опыт. |cffFF8000Член группы, уже находящийся внутри подземелья, получил бафф по изменению сложности. Для заклинателей не применен бонус к силе заклинаний. ВСЕ члены группы должны выйти из подземелья и войти снова, чтобы получить изменение баланса.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(30004, "|cff4CFF00[SoloCraft]|r |cffFF8000 %s exited to %s - Reverting Difficulty Offset: %0.2f. Spellpower Bonus Removed", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "|cffFF0000[СолоКрафт]|r |cffFF8000 %s покинул %s - Возврат изменения сложности: %0.2f. Бонус к силе заклинаний удален: %i", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(30005, "Enabled", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Включено", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(30006, "Disabled", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Отключено", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
