DELETE FROM `trinity_string` WHERE `entry` IN (1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166,
                                               1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176,
                                               15005, 15006, 15007, 15008, 15009, 15010, 15011, 15012, 15013, 15014,
                                               15015, 15016, 15017, 15018, 15019, 15020, 15021, 15022, 15023, 15024,
                                               15025, 15026, 15027, 15028, 15029, 15030, 15031, 15032, 15033);
INSERT INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `content_loc9`, `content_loc10`, `content_loc11`, `content_female`, `content_female_loc1`, `content_female_loc2`, `content_female_loc3`, `content_female_loc4`, `content_female_loc5`, `content_female_loc6`, `content_female_loc7`, `content_female_loc8`, `content_female_loc9`, `content_female_loc10`, `content_female_loc11`) VALUES
(1157, "All config are reloaded from configuration file.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1158, "==========================================================", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1159, "|--------------------------------------------------------|", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1160, "|            | Alliance |  Horde   | Neutral  |  Total   |", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1161, "          Alliance/Horde/Neutral/Total", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1162, "| %-10s | %8u | %8u | %8u | %8u |", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1163, "%-10s = %6u / %6u / %6u / %6u", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1164, "Count", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1165, "Item Ratio", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1166, "|            | Alliance |   Horde  | Neutral  |  Amount  |", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1167, "          Alliance/Horde/Neutral/Amount", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1168, "Gray", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1169, "White", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1170, "Green", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1171, "Blue", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1172, "Purple", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1173, "Orange", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1174, "Yellow", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1175, "Amount of %s items is set to %u.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1176, "Items ratio for %s is set to %u.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15005, "|cff1eff00Your current balance is:", NULL, NULL, "|cff1eff00Aktuelles Guthaben ist:", NULL, NULL, NULL, NULL, "|cff1eff00Ваш текущий баланс:", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15006, "Thank you for your purchase. Your new balance is:", NULL, NULL, "Danke für deinen Einkauf, deine neues Guthaben beträgt:", NULL, NULL, NULL, NULL, "Спасибо за покупку. Ваш остаток на балансе:", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15007, "You can't afford this!", NULL, NULL, "Das kannst du dir nicht leisten!", NULL, NULL, NULL, NULL, "Вы не можете себе этого позволить!", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15008, "Item transmogrified.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Предмет успешно трансмогрифицирован.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15009, "Equipment slot is empty.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Слот для экипировки пуст.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15010, "Invalid source item selected.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Выбран недопустимый исходный предмет.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15011, "Source item does not exist.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Исходный предмет не найден.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15012, "Destination item does not exist.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Конечный предмет не найден.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15013, "Selected items are invalid.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Выбранные вещи являются недействительными.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15014, "Not enough money.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Не хватает денег.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15015, "You don`t have enough tokens.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Вам не хватает жетонов.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15016, "Transmogrifications removed.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Трансмогрификация удалена.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15017, "There are no transmogrifications.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Данный предмет не трансмогрифицирован.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15018, "Invalid name inserted.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Введено неверное имя.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15019, "Head", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Шлем", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15020, "Shoulder", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Плечи", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15021, "Shirt", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Рубашка", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15022, "Chest", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Грудь", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15023, "Waist", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Пояс", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15024, "Legs", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Ноги", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15025, "Feet", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Ступни", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15026, "Wrists", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Наручи", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15027, "Hands", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Рукавицы", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15028, "Back", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Плащ", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15029, "Main Hand Weapon", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Оружие (Правая рука)", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15030, "Secondary Hand Weapon", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Оружие (Левая рука)", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15031, "Ranged Weapon", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Дальний бой", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15032, "Tabard", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Гербовая накидка", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15033, "Account", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Учетная запись", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
