local talk_time = {1000,10000} --聊天刷屏时间间隔 1秒 = 1000
local guild_talk_time= {10000,30000} --公会聊天刷屏时间间隔 1秒 = 1000

--local ns = "SELECT name FROM creature_template WHERE entry BETWEEN '14500000' AND '14600000'"  --选取数据库的数据作为npc名字源,留空时使用npc_name.lua设置的名字
--local ns = "SELECT name FROM characters.ai_playerbot_names"
local ns = ""

local t = {}


local npc_text = {[0] = {1,1},


----------------------从这儿开始添加聊天文本-------------------------
"收银鳞胸甲,5G一件.",
{"听说肉沫在和二木搞基来着","真的假的?","假的.其实肉沫在和猪兔在搞基.","666","好基友一被子{大笑}"},
{"兰总出来开车啊!~~(破音)","兰总今天没上线呢","请注意,前方撤王出没","溜了溜了","溜了溜了 + 1","溜了溜了+2","溜了溜了 + 3","溜了溜了 + 4","溜了溜了 + 10086"},
"25黑龙4200左右GS 小德SM FS 菜刀 带属性密15=10 效率了 今天不参加以后也没人组野团打25黑龙的。",
"400G一组收空气，100一个收 [冰冻宝珠] ",
"治疗求组 PTSL刷刷队伍",
"G 带刷等级的在不",
"SW多少人能打啊",
"花Q",
"哨兵招收SS,要求GS 4500+，6专业及以上，活动时间周二、三晚8点到11点半，合适的朋友可包10人团位置。",
"收泰坦矿，有的代价MMM",
"25NAXX5分团速度来人·来爆炸团刷治疗··24=1``",
"无限PTSL来非板甲DPS 治疗",
"[孤狼之华丽护手]有要的吗超低价格",
"10人奥杜尔老一，来个会勾栏的",
"治疗求组PT 试炼",
"YXSL  来DPS  带GSM",
"PTSL 来T 锁甲DPS",
"SW10人就能搞了吧？",
"25黑龙 网卡别密 带属性4300+ 各职业。不参加25RIAD的号。",
"10人黑龙有没有SM NQ SS 来？",
"20人SW。。。人是不是太多了 R都难R啊",
"hsl开组来t dps",
"【八零的回忆】全新公会收人。全新DKP面向全服务器招收各类玩家，无装备基础要求，稳定在线即可。活动时间每周456晚7点30-11点。为优化团队现招收奶S奶D。",
"10人便当奥杜尔 新CD   来DPS和治疗 带GSM =6",
"英雄联盟2团备战TOC招收NQ SM MS，全新团队，全新DKP，诚招各路朋友一起体验游戏乐趣，有意的MMM",
"HSL 来T  奶  DPS",
"SW幻化团 下午无聊  20人打不能上YY勿扰。",
"收一个 [内燃护腕]  有的卖",
"25NAXX5分团速度来人·来爆炸DPS``20=5``",
"YXSL  老2  来个DPS",
"25开车来皮锁老司机 =2或者不需求 [泰坦禁卫]的板甲",
"UDL10人团取消，改为SW幻化团队，20人左右开打，要求能上YY，谢谢大家=10",
"收 [无限之尘] [无限之尘]",
"10ULD  来个4100+的近战和NQ MS",
"收多专法师，代价M~要脱坑的哟。",
"25开车来布皮锁老司机",
"收G 收G，带比例MM我",
"10人便当奥杜尔  来DPS和治疗 =6",
"HSL  来强力T和DPS   4200+的队伍  速度打完吃饭",
"[奥杜尔团队的荣耀（10人）]半成就团。4守护开打。来NQ   双修SMSS带GSMMMMM",
"25NAXX,...........5分团，来DPS,  需求饰品的近战远程呢，赶紧了",
"10人ULD新CD！！！！来强力NQ！！MS！！！！！还有ZS！！！强力碾压团队！！来的带上GS   7=3    起码打到UG",
"HSL  来强力T和DPS   最后一波   速度",
"有没有25人黑龙的？",
"YXSL来各职业袋装等MMMMMMMMMMMM",
"PTSL 刷刷队 来两个DPS 皮锁优先啊  4=1  ",
"收 永恒火20！空气15！土6！暗影5！水4！生命30！萨矿15！萨锭30 ！北地皮20/组 厚北皮130/组 冰冷龙鳞1G蛛魔几丁质1G冰虫鳞片2G 冰冻宝珠100符文宝珠210！付款邮寄秒",
"[霜纹布] [北地皮]各25组，要的密",
"英雄联盟2团备战TOC招收NQ SM MS，全新团队，全新DKP，诚招各路朋友一起体验游戏乐趣，有意的MMM",
"[冰冻宝珠]=110G, [碧蓝魔线]=32G！！",
"BWL幻化队  来的M 已经2人了  不要AL",
"日常R点比大小 200G一次 来的M",
"老炮儿公会 集两个10人ULD全通团的公会。现为备战TOC 特招DZ  AM NQ 邪DK 来了就是主力。要求有一定装备基础 新人进团BOSS双倍分。给我一个稳定的你还你一个优质的",
"YXSL,新进度，每日一刷， 来4000+治疗，法系DPS，LR，来的MM",
"YXSL, 来4000+治疗，法系DPS，LR，来的MM",
"收王者巨皓绯色石恐惧紫黄石120G霜纹4G冰棘蛇信32g巫妖花151G/组损坏项链88g支持cod",
"<流金岁月》招收各职业精英玩家~全心DKP全新CD欢迎各职业大神加入欧，让我们一起感受魔兽组曾经给我们带来的基情与欢乐，活动时间456每晚8点-11点~期待你的加入！",
"1:150G 出售 100个水晶币。。 有需要的MMM",
"出售/代工奥杜亚226装等布皮锁板制作类腰带鞋子,收冰冻宝珠100g符文宝珠220g王者琥珀绯色红惧石紫黄晶121g泰坦神铁矿石125g萨隆邪铁矿石15g,土7.1火26.5空气16暗影5水",
"收永恒之土7G 永恒生命32G组火焰26空气16暗影5水7萨矿15.5泰坦126冰冻宝珠101北地皮22G蛛丝冰虫皮1.5支持 cod 秒取 ",
"150收巫妖花   支持邮",
"HSL来T和DPS",
"出售联盟 9 专业 4700GS DZ  幽灵虎 暴雪熊 奥杜尔成就龙  需要的MMM",
"你这个小 杂 碎，老 子 要让你知道知道，踢到铁板了",
"好吧，平静的生活一去不复返了，你赢了，有本事就呆这里，我要你好看",
"你无聊，闲的 蛋 蛋 疼了 是吧，非常好",
"杀我是要付出代价的，惨痛的代价，终身难忘哦",
"你丫就算跑了，也别想在这个服务器呆下去了， 草",
"你这个熊孩子，不知道天高地厚，知道我是谁吗",
"你想惹事，我奉陪，谁怕了谁删号",
"别跑哦，一会就有好戏看了",
"有种呆这里，不揍的你 妈 都不认识你，我就不混了",
"你给我等着，有 种别跑",
"草 泥 马，你不想混了？找死啊",
"有没有H SL的",
"[高尚套牌]80币出，1：135收币~有需要的密~~~~~~~~~~~~",
"出售4500 单专业NS 要的MMM同账号有3职业 FS4200 DK3200 SM4500没时间 有意的MMMAG门口看号",
"10人蓝龙来 老司机",
"ULD开车队来各种老司机",
"安其拉神殿幻化来T和治疗",
"HSL 来个锁甲输出。",
"10人黑龙来奶骑，1T，8=2~~~~~~~",
"新建公会《后宫》备战TOC招收各种稳定的人员.满80 稳定就行。。每周12晚上7.30点到11点25人活动。有意的私聊。其他时间工会组织10人团提升！",
"HSL 来个能抗的主的T  可以啦 4=1",
"公会《英雄联盟》1团招收各（满专业）稳定职业，补充4专以上双休MS  SM 提供10人团！进度25H 9/10，开荒 阿加隆！10H进度全通！2团 满专业团队招各稳定职业 只要求",
"10人黑龙来个奶骑或者戒律牧 ，9=1能拉人~~~~~~~~~~~",
"[空中的威胁]来的MMMMMMMMMMM",
"出售 [无限之尘]70 [霜纹布卷]25{胜利}",
"骗子上线了，大家来围观啊。。。。",
"风在吼，吗在叫，点卡在燃烧，暴雪在偷笑",
"门神三自然，时光加点燃，奈法红加蓝，本周全完玩",
"锄禾日当午，盗贼最辛苦，影袭加刺骨，一按一下午！！",
"要爱不要魔兽，求组真爱~~。。。",
"萨满求组naxx。。。马上80。。。。。",
"纳格兰鲜血竞技场任务有做的没。。。。",
"祖达克竞技场任务，来个治疗。。。",
"监狱开组了，随便来。。。",
"狗日的，骗子死全家。。。。。",
"毛人毛会，就会黑装备，大家不要去。。",
"死矿来的密密，3=2！！",
"杀部落的组起。。。。",
"杀部落的有人来么？？。",
"杀联盟的组起。。。。",
"杀联盟的有人来么？？。",
"有一起组队任务的吗？",
"技不在精，脸滚就赢，键不在多，会biu就行",
"怒焰来的密密，3=2！！",
"屌丝武器战，打架靠风扇，cd一分半，转完就完蛋",
"奥山国家队开组。77+的来。。。。",
"哀嚎开组了，随便来。。。。",
"各色80级紫色散件，便宜卖啦！！。",
"卖点卡，5300金，有担保可以先卡。。。",
"他是个骗子，大家不要听他的。。",
"五十六个萨满，五十六个渣，五十六个移动荣誉随便杀！",
"一代补丁一代神，代代补丁有法神。。",
"dk多如狗，骑士满街走。。。。",
"5000G收点卡！先卡后金，公会会长担保~~~",
"25人Htoc公会金团，来强力消费，看金进组。。。",


}

local npc_text_guild = {[0] = {1,1},

----------------------从这儿开始添加聊天文本-------------------------

"10人ptoc公会团开组,来的扣1",
"25人udl成就团开组,来T,奶DPS,还有5个坑.",
}


local npc_name = {[0] = {1,1},

----------------------从这儿开始添加npc name-------------------------

	"好名字都给畜生用了",
	"范坚强",
	"动若疯兔",
	"刁丝",
	"迪普",
	"发粪涂墙",
	"疯豹打鸡",
	"岗坂日传",
	"苟日",
	"怪很强你先上",
	"光看我能怀孕吗",
	"洞茎皆宜",
	"洞茎结合",
	"桂舔",
	"劣人",
	"刘芒",
	"柳下挥",
	"撸智深",
	"路边一色狼",
	"马麦辟",
	"买完东西卖旁边",
	"卖完东西买旁边",
	"满脑子肌肉",
	"没意思",
	"梅闻化",
	"镁屡",
	"妹汁",
	"弱智儿童欢乐多",
	"沙法",
	"傻曼",
	"深入裙中",
	"砂锅那么大的拳头",
	"生如夏花",
	"师太你就从了老衲吧",
	"施主您装B",
	"史太农",
	"屎里飘香",
	"兽兽力量大",
	"舔她我来顶",
	"清明",
	"河图",
	"日不死你我懦夫",
	"你的老婆和我",
	"波大径深",
	"发型始终不乱",
	"发型还是不乱",
	"发型不乱",
	"我是野生的",
	"我是家养的",
	"拉开裤链不见了",
	"用脸滚键盘",
	"叫兽没文化",
	"奥八马",
	"鸭梨山大裸死",
	"就爱喝红牛",
	"苍井不空了",
	"武松你给我出来",
	"欧巴肛漏啥",
	"跪下唱征服",
	"裸死福",
	"牛头人卡门",
	"哇咔咔",
	"舔咪咪",
	"呜喵王之怒",
	"尸王",
	"花满楼",
	"松下裤裤子",
	"松下带带子",
	"无聊",
	"雷人",
	"午夜凶灵",
	"瘦人",
	"魔高一丈",
	"多皮",
	"三皮",
	"东京很热",
	"加勒比很嗨",
	"龙傲天",
	"秦肖娜",
	"秦寿",
	"小虾米",
	"刹那芳华",
	"高大全",
	"陆仁甲",
	"钱水廷",
	"马甲",
	"蓝翔技校",
	"加里敦",
	"传说哥",
	"花菇凉",
	"带刺黄瓜最好玩",
	"扯蛋",
	"羊教授",
	"车震狂魔",
	"风吹屁屁凉",
	"百撕不得骑姐",
	"土土的包子",
	"大射狼",
	"闹太套",
	"千里之外",
	"发如雪",
	"牛仔很忙",
	"杀戮盛宴",
	"屁股扭扭",
	"小尾巴",
	"弟弟大洞洞大",
	"小湿弟",
	"冰封王座",
	"来一发",
	"当午",
	"淡藤",
	"单季稻",
	"大学僧",
	"大象掉进蚂蚁洞",
	"大湿胸",
	"大撸伤身",
	"妲菲姬",
	"达纯吕",
	"锤子",
	"朝三暮四",
	"挨踢精英",
	"米虫",
	"名字长了在他念你名字时秒杀他",
	"名字太短容易被敌人记住",
	"内裤我一直用雕牌",
	"那一夜不是我",
	"那一夜就是我",
	"男娼起义",
	"你妹",
	"双季稻",
	"我发飙了",
	"胸有春鸽",
	"楚囡",
	"楚侣",
	"锄禾",
	"臭鼠标拿开",
	"草泥马",
	"不要啊",
	"不明觉厉",
	"不辣的皮特",
	"别动我开枪",
	"边泰",
	"板凳",
	"奥特曼",
	"爱过知情重",
	"看完A片换B片",
	"不好意思射到你脸上",
	"风吹逼毛两边倒",
	"两腿劈开就有钱",
	"打不过我就跑",
	"劳资禽兽不如",
	"风吹几吧毛不动",
	"替天行房",
	"PK实战发型不乱",
	"狼牙山我装死",
	"董存瑞举的是我",
	"黄继光都没堵住我",
	"化妆化的跟鬼一样",
	"比如花还如花",
	"跪下给我唱征服",
	"东南西北方不败",
	"行者孙",
	"孙行者",
	"没有尾巴和你一样",
	"PK起来一手汗",
	"胸比头大",
	"我比姚明高",
	"天啦你真高",
	"贱人风暴",
	"伱妈",
	"尼玛",
	"偶把你来哄",
	"别跑挨打不痛",
	"小不点",
	"小布丁",
	"请随便",
	"萌萌哒",
	"波哥大",
	"摸摸大",
	"么么哒",
	"你大爷",
	"你爷爷临死前",
	"我的脸有六十码",
	"我是骑兵我有马",
	"我是步兵我没马",
	"贾老实",
	"他二舅",
	"二比",
	"兰州大烧饼",
	"路过帮顶",
	"傲娇",
	"查水表",
	"五毛",
	"柏拉土",
	"洛丽塔",
	"铁石心肠",
	"猥小琐",
	"豹驹",
	"不能无敌炉石",
	"无齿下流",
	"请收下我的膝盖",
	"款爷",
	"倍儿爽",
	"鸡鸡歪歪",
	"孬昆",
	"丧失",
	"猛母三千",
	"妙比生花",
	"拤管",
	"阿多根",
	"霍咯",
	"新人杀手",
	"颤抖吧凡人",
	"燃烧吧小宇宙",
	"王霸",
	"五行缺德",
	"往事随风",
	"穷挫矮",
	"黑穷丑",
	"龟头太浪",
	"郭德钢",
	"郭德银",
	"郭德铜",
	"郭德铁",
	"郝建",
	"耗子扛枪",
	"何谢",
	"虎躯巨震",
	"灰机",
	"坚持不泄",
	"见过大爷手淫没",
	"津液你会不会来",
	"经典含具大长茎",
	"景阳岗上挨过打",
	"九阴争茎",
	"牛Ｂ哄哄震山东",
	"农夫三拳有点痛",
	"女友糖尿病害我蛀牙",
	"欧碧奇",
	"欧谢特",
	"贫僧法号能抗",
	"虔诚信仰",
	"强撸灰飞烟灭",
	"请输入你的密码",
	"请输入你的帐号",
	"日出东方",
	"铁掌奶上飘",
	"魏申京",
	"一年硬两次",
	"一紧张就射",
	"我也用妇炎洁",
	"小泉纯一狼",
	"以茎制洞",
	"我杀了如来就是佛",
	"我是被逼的",
	"我是自愿的",
	"小不死",
	"刚从动物园里逃出来",
	"兽兽的",
	"恭喜你成为幸运玩家",
	"波涛胸涌",
	"就不给",
	"给点吃的吧",
	"碧油姬",
	"刀郎没我冲动",
	"肉肉的",
	"麻辣鸡丝",
	"红烧牛肉",
	"奶奶滴个胸",
	"偶麦噶",
	"偶滴神",
	"大地母亲忽悠着你",
	"变形金刚",
	"鲜血与荣耀",
	"力量与雷鸣",
	"偶可是党员",
	"天使巴尔",
	"酱紫",
	"官人我要",
	"大爷过来玩",
	"没脸贱人",
	"无赖",
	"胡来",
	"依网情深",
	"小蛮腰",
	"倪友丙",
	"我来组成头部",
	"咸蛋超人",
	"矮小缺",
	"高富帅",
	"白富美",
	"鹅考",
	"牛叉叉",
	"叉叉圈圈",
	"二货",
	"没奶妈喂你",
	"就是没有奶",
	"复活吧我的勇士",
	"为你而战我的女士",
	"沉迷",
	"妞给爷笑个",
	"爷给你笑个",
	"他大舅",
	"齐观严",
	"小清新",
	"看下又不犯法",
	"那一贱的风情",
	"观阴大湿",
	"今夜菊部有雨",
	"大种马",
	"小种马",
	"搞毛",
	"恰同学骚年",
	"露骨",
	"新鲜的排骨",
	"甘倪媚",
	"欧巴",
	"逗比",
	"沉默的猖狂",
	"大宝",
	"小宝",
	"攻受兼备",
	"银蹈燕",
	"银贼",
	"英年早肥",
	"英年早废",
	"迎风丑死你",
	"有事秘书干",
	"有种就看我一眼",
	"鱼别扔",
	"原来名字可以这么长",
	"云心如月",
	"起名字真他妈难",
	"怎么看都有型",
	"翟楠",
	"战士向右",
	"站住劫个色",
	"找乐子",
	"酒精考验",
	"看的我极端郁闷中",
	"夸厦",
	"胯下有奇迹",
	"拉链夹到鸟",
	"老毕",
	"老不死",
	"老纳成全了师太",
	"老衲要射了",
	"李菊福",
	"理查德泰深",
	"理查德深",
	"日在落日打怪",
	"圣光之衣",
	"一次硬半年",
	"三拳打死武松",
	"闪开老衲要射",
	"五火球教主",
	"羊怪开火",
	"一招不秒撒腿就跑",
	"一发火球引发的血案",
	"我掩护你去送死",
	"我以为我是美女",
	"下气通",
	"夏剑",
	"夏柳",
	"萧涩郎",
	"小撸怡情",
	"小丝妹",
	"谢主龙恩",
	"姓冲动",
	"胸怀大痣",
	"夜未央",
	"路见不平拔刀自刎",
	"把鼠标拿开",
	"会接生的男人",
	"都是太阳惹的祸",
	"我顶你挺",
	"我挺你顶",
	"一步一卡卡的潇洒",
	"我是国宝别打我",
	"看到色狼就装死",
	"我是做了手术的女人",
	"让公主受精了",
	"阴小湿大",
	"毛茸茸的小可爱",
	"戴个奶罩多点防",
	"愿圣光与你同在",
	"饭太稀",
	"菊花蚕",
	"喜当爹",
	"艾田游",
	"武藤兰",
	"骷髅精灵",
	"动感光波",
	"坏菜不予",
	"罗奔",
	"身无二两肉",
	"天上童姥",
	"打酱油",
	"范建",
	"薇薇抖奶",
	"海绵宝宝",
	"你白",
	"无名",
	"梅芬",
	"无人性",
	"弱爆了",
	"屌炸天",
	"毛人",
	"姜丝",
	"郝仁",
	"送菜",
	"很黄很暴力",
	"很陈很冠希",
	"马拉戈比",
	"我吃素",
	"石榴姐",
	"吴迪",
	"姐夫",
	"我擦",
	"我勒割草",
	"善良的牲口",
	"我爱一条柴",
	"冰火之歌",
	"泰兰德的香蕉",
	"小舔舔",
	"酷币勒",
	"七尺大乳",
	"机油",
	"抠脚女汉子",
	"申京并",
	"狐狒",
	"笨拉灯",
	"孩他爹",
	"孩他妈",
	"欠揍",
	"很爱很爱你",
	"孤独的守望者",
	"根本停不下来",
	"快到碗里来",
	"快乐崇拜",
	"赵史",
	"者行孙",
	"这他喵也行",
	"甄伟大",
	"朕射你无罪",
	"职业玩家",
	"指着太阳说日",
	"肿么办",
	"猪哥亮",
	"抓根宝",
	"庄碧凡",
	"装B挨打E然潇洒",
	"走位风骚",
	"最爱捡肥皂",
	"醉过知酒浓",
	"昨夜第七天堂",
	"Imoiseybi",
	"Ypedrireatil",
	"Yeayeuco",
	"Eroe",
	"Anereboi",
	"Edetave",
	"Nieudachow",
	"Erflai",
	"Sheadeat",
	"Penoildea",
	"Timoxeobing",
	"Iementnoliin",
	"Ohepitiomed",
	"Onsrero",
	"Olerontat",
	"Ajealipie",
	"Edwiakestua",
	"Itarphosaoe",
	"Storilei",
	"Raguirmyay",
	"Arla",
	"Abilydile",
	"Erurastoi",
	"Itiolene",
	"Ivtreleait",
	"Zoeberla",
	"Bereoglien",
	"Natniehesfi",
	"Filyneipna",
	"Apiesima",
	"Chaefondwadi",
	"Attenoi",
	"Oryatee",
	"Nabapotii",
	"Aedyst",
	"Ofafuocel",
	"Acochbatioe",
	"Yiurera",
	"Eyuneerao",
	"Toetetryra",
	"Uilidifyma",
	"Sayocono",
	"Inibaee",
	"Ecyon",
	"Oneepantie",
	"Isasimyingul",
	"Barouryi",
	"Enoobli",
	"Espeligeli",
	"Tioatiayly",
	"Neebnaint",
	"Emotieistsa",
	"Rayetacoama",
	"Rifpyeloam",
	"Deeaonk",
	"Erilieregre",
	"Issphabrala",
	"Waco",
	"Ialisteg",
	"Isibeid",
	"Foloasi",
	"Eiverehi",
	"Ulisyno",
	"Attefi",
	"Olatenu",
	"Estadeou",
	"Ecogra",
	"Anonveyede",
	"Aronawadeo",
	"Imeiussonges",
	"Flotoyena",
	"Imraanecerov",
	"Atnaeldiepre",
	"Atineahni",
	"Oirthmauru",
	"Uwenedayo",
	"Maaiapheti",
	"Orabmoalbuor",
	"Iqpa",
	"Eriliab",
	"Oidusrabo",
	"Buimoirmaki",
	"Boqelot",
	"Piilidcha",
	"Ibespeu",
	"Isdoac",
	"Erbyaus",
	"Ayasyonerak",
	"Egaera",
	"Ohlme",
	"Anaifenoent",
	"Roaozpry",
	"Reivre",
	"Mohidehyan",
	"Utinecri",
	"Iyisbal",
	"Ioalihal",
	"Coero",
	"Deaba",
	"Urtyonechepo",
	"Delete",
	"Ulbue",
	"Ercadeoechi",
	"Yeckehtocip",
	"Guitep",
	"Kyamengumra",
	"Laeqamfoa",
	"Adastastadi",
	"Aniaopensi",
	"Denor",
	"Riauvout",
	"Caohathughog",
	"Yeneilon",
	"Ecosiiciney",
	"Aogilah",
	"Eutyimartin",
	"Iefufiaran",
	"Oponeici",
	"Eoiama",
	"Oinephsto",
	"Soistreferty",
	"Eliarohad",
	"Moicka",
	"Nuomemayga",
	"Gisyleoae",
	"Yugruanecor",
	"Andetasha",
	"Esdi",
	"Aysuitmadi",
	"Nateosefriec",
	"Eigountorhe",
	"Ineurbadeal",
	"Yeeftetruupo",
	"Ylubohtsechi",
	"Ahinetoii",
	"Nooeviro",
	"Itiibi",
	"Aylocimi",
	"Moielocuhi",
	"Phaiyoeenup",
	"Neapcaveic",
	"Oeerula",
	"Osellag",
	"Iseerucimy",
	"Ogea",
	"Aenitanu",
	"Psyeabe",
	"Cheinty",
	"Eidberpretre",
	"Aniliak",
	"Stiepaalu",
	"Amaerliskoor",
	"Urtiuara",
	"Yayenme",
	"Eidchar",
	"Sioylamne",
	"Gapacfle",
	"Autuockus",
	"Duoramtuvi",
	"Yriailahne",
	"Aieair",
	"Isulte",
	"Isetya",
	"Eereleyrl",
	"Etiotur",
	"Oeta",
	"Elneontexep",
	"Istro",
	"Esideiudva",
	"Rauci",
	"Coap",
	"Oarkonguban",
	"Erotaleesmva",
	"Teliygcine",
	"Elfoshlui",
	"Eclyor",
	"Typoryaida",
	"Erlo",
	"Wiepok",
	"Aaiay",
	"Ecpra",
	"Moicasgias",
	"Ococuelat",
	"Gaeaonel",
	"Ienowlyhuid",
	"Eokioa",
	"Eayseoy",
	"Antilytysho",
	"Ryoun",
	"Noze",
	"Einuorplo",
	"Eadozya",
	"Opoac",
	"Ygasi",
	"Emiaenoyum",
	"Rychi",
	"Leie",
	"Clirarheathi",
	"Isastoisesab",
	"Yohoriui",
	"Oritaboisa",
	"Actte",
	"Yitarni",
	"Irotia",
	"Ibdiengeoeng",
	"Maolimuibe",
	"Aewalu",
	"Niato",
	"Roipaew",
	"Acebreor",
	"Qeatayaa",
	"Mowo",
	"Eosleourd",
	"Liiabifpei",
	"Yedia",
	"Reozalfeceac",
	"Ciinedeonye",
	"Meamenyoand",
	"Yaershale",
	"Lieseimpa",
	"Ysyom",
	"Omei",
	"Raureepeu",
	"Gniuraaviri",
	"Sphileeate",
	"Puopee",
	"Erumixdi",
	"Wheza",
	"Deisyipere",
	"Itiinvigui",
	"Aleoyetew",
	"Oerolater",
	"Itegae",
	"Disceus",
	"Nacoco",
	"Yrakietocto",
	"Tianotrua",
	"Eioneoin",
	"Urlentarcuem",
	"Oraey",
	"Atiteotuy",
	"Oitira",
	"Dion",
	"Meseocatse",
	"Saopo",
	"Teoplu",
	"Liinrielto",
	"Ilsto",
	"Rigyanentagh",
	"Elitor",
	"Reafuca",
	"Inniusogave",
	"Odorteliieh",
	"Ulorla",
	"Mouseyfa",
	"Pepha",
	"Xalioncize",
	"Dalural",
	"Uneiucke",
	"Isyemili",
	"Eneyilk",
	"Izoneroonpe",
	"Ealeyeg",
	"Izfrebete",
	"Iokoabe",
	"Lyox",
	"Ecoeric",
	"Boagyamiye",
	"Orarosmne",
	"Oahae",
	"Ileimriooz",
	"Ouhoic",
	"Miaxiye",
	"Sootraeci",
	"Echceliei",
	"Emaetapha",
	"Arkdreae",
	"Esmeaca",
	"Blaiiacyce",
	"Ysatenpro",
	"Ideptuadeab",
	"Initis",
	"Liropar",
	"Ogriuaiop",
	"Oabuet",
	"Tipeesusuyo",
	"Oteefertiti",
	"Ipaxiyosu",
	"Ankaerinlyo",
	"Itoiedta",
	"Lepecku",
	"Oirottreine",
	"Epiinimmacu",
	"Eaosisiic",
	"Reeat",
	"Asoyamidea",
	"Eteystaco",
	"Aeplaepti",
	"Oyiciiok",
	"Ipraisac",
	"Yoeariufri",
	"Acihunleeh",
	"Aerteab",
	"Iulal",
	"Ogmo",
	"Ierpen",
	"Mipseo",
	"Noliepaeey",
	"Wheeane",
	"Uribige",
	"Eluizfisoa",
	"Psyaopisrope",
	"Igihyiosm",
	"Inrafro",
	"Huiniyrler",
	"Acaryara",
	"Yeuseeales",
	"Alist",
	"Dacysetebre",
	"Ycoenum",
	"Ayecev",
	"Ifroaisial",
	"Enosterwicli",
	"Iisa",
	"Ileabla",
	"Kibiueab",
	"Yyocewa",
	"Oarustanib",
	"Ibinoyekna",
	"Gyfroeenteul",
	"Imelep",
	"Amoom",
	"Eoselolindho",
	"Paiul",
	"Ialoa",
	"Uitreyoel",
	"Tierycu",
	"Oraker",
	"Otelpauogfi",
	"Oomok",
	"Ditusaeyi",
	"Sateoislu",
	"Orotalimare",
	"Ejaunryi",
	"Zageacoulat",
	"Iedo",
	"Itico",
	"Madehoad",
	"Olariong",
	"Astruhy",
	"Emaweolfle",
	"Imiliseflumo",
	"Tiodieri",
	"Moripne",
	"Eloidgai",
	"Antoonomo",
	"Stero",
	"Itza",
	"Traulpo",
	"Eizte",
	"Idrissre",
	"Yaly",
	"Imeasumca",
	"Iddta",
	"Anitureic",
	"Qunacutodu",
	"Laubneesca",
	"Ummiat",
	"Tiofateur",
	"Fiogytiyasno",
	"Esrefean",
	"Istov",
	"Atoushugry",
	"Esmea",
	"Etastem",
	"Icedulyickat",
	"Erlira",
	"Boeuete",
	"Oneiaron",
	"Oare",
	"Nesemymaana",
	"Eikoun",
	"Onerote",
	"Denito",
	"Veoyoane",
	"Enirey",
	"Eriidoe",
	"Eiph",
	"Fidisitecis",
	"Edecalucaul",
	"Homamo",
	"Arerpro",
	"Uruoer",
	"Atcaomeraest",
	"Woerle",
	"Engess",
	"Aquard",
	"Ereomineo",
	"Isillniivnae",
	"Eoretito",
	"Aenu",
	"Sheneanat",
	"Tuissusnioc",
	"Alanayzien",
	"Tugrueckige",
	"Reelploi",
	"Aska",
	"Enindio",
	"Trionaratin",
	"Priuch",
	"Apein",
	"Baotuiele",
	"Olupah",
	"Gafatececi",
	"Nielsu",
	"Cheuehry",
	"Ejree",
	"Oryateoar",
	"Deansdo",
	"Dioalemim",
	"Energreu",
	"Osiolprahyay",
	"Itesoaan",
	"Liee",
	"Ilitonere",
	"Iereche",
	"Entgairtear",
	"Verianeitom",
	"Paeu",
	"Ehafne",
	"Yeyng",
	"Osatpao",
	"Fienhoisfa",
	"Onumzeshoto",
	"Gealagel",
	"Coseso",
	"Rorcai",
	"Aogev",
	"Griasusqe",
	"Gyolagcaa",
	"Uoirre",
	"Ipenyve",
	"Iayakas",
	"Sehnama",
	"Bioulamti",
	"Vapialeiyi",
	"Reviadyerla",
	"Etdora",
	"Pialplikeri",
	"Soospal",
	"Yliionteass",
	"Tisoteodo",
	"Esitacaem",
	"Annathuehaf",
	"Ouna",
	"Remaarlaeong",
	"Igte",
	"Liafei",
	"Ytoatigy",
	"Pofree",
	"Upnaliex",
	"Upiya",
	"Neretiteor",
	"Ipceatio",
	"Leowisbidi",
	"Eshush",
	"Aneuitil",
	"Ejnoojoraf",
	"Ophedigad",
	"Icaywfle",
	"Oratanefime",
	"Akieroneack",
	"Ujoapye",
	"Soae",
	"Poom",
	"Neouslaa",
	"Theiveala",
	"Zeestateptri",
	"Otogillinap",
	"Uodi",
	"Oabi",
	"Odneame",
	"Apogoply",
	"Aecheadra",
	"Ilincetre",
	"Eseumcoi",
	"Aceeiv",
	"Naceile",
	"Rooaceupi",
	"Epiyetuu",
	"Udigaraagga",
	"Nureo",
	"Ubyended",
	"Ulyriurornu",
	"Otopo",
    
    
    
}
 

t.t = {
    talk = npc_text,
    guild_talk = npc_text_guild,
}

t.cc = {"C79C6E","F58CBA","ABD473","FFF569","FFFFFF","C41F3B","0070DE","69CCF0","9482C9","FF7d0A" }

t.init = function(s)
    math.randomseed(tostring(os.time()):reverse():sub(1, 7))
    s.d = npc_name or {}
    if (ns ~= "") then
        local q = WorldDBQuery(ns)
        if (q) then
            repeat
                table.insert(s.d,q:GetString(0))
            until not q:NextRow()
        end
    end
end
t:init()


t.fg = function(s,talkType)
    math.randomseed(tostring(os.time()):reverse():sub(1, 7)) 
    local i = math.random(#s.t[talkType]) 
    s.t[talkType][0][1] = i 
    s.t[talkType][0][2] = 1 
    if (type(s.t[talkType][i])=="string") then 
        return s.t[talkType][i] 
    elseif (type(s.t[talkType][i])=="table") then 
        s.t[talkType][0][2] = s.t[talkType][0][2] + 1 
        return s.t[talkType][i][1] 
    end 
end

--生成当前聊天文本
t.dt = function(s,talkType) 
    local i = s.t[talkType][0][1] 
    local ti = s.t[talkType][0][2] 
    local t = "" 
    if (type(s.t[talkType][i])=="string") then 
        t = s:fg(talkType) 
    end 
    if (type(s.t[talkType][i])=="table") then 
        if (#s.t[talkType][i] < ti) then 
            t = s:fg(talkType) 
        else 
            t = s.t[talkType][i][ti] 
            s.t[talkType][0][2] = s.t[talkType][0][2] + 1 
        end 
    end 
    return t 
end

--创建公共聊天事件
CreateLuaEvent(function() 
    local n = t.d[math.random(#t.d)] 
    SendWorldMessage(string.format("|cFFFFC0C0[世]|r|cff%s|Hplayer:%s|h[%s]|h|r:|cFFFFC0C0%s|r",t.cc[math.random(#t.cc)],n,n,t:dt("talk")))
end,
talk_time[1],talk_time[2],
0)

--创建公会聊天事件
CreateLuaEvent(
function() 
    local n = t.d[math.random(#t.d)] 
    SendWorldMessage(string.format("|cFF40FF40[会]|Hplayer:%s|h[%s]|h:%s|r",n,n,t:dt("guild_talk")))
end,
guild_talk_time[1],guild_talk_time[2],
0)


--处理密语,邀请封包
RegisterServerEvent(5, function(_, p, w) 
    local c = p:GetOpcode() 
    if (c==0x095) then 
        local t = p:ReadULong() 
        local l = p:ReadULong() 
        local n = p:ReadString() 
        local m = p:ReadString() 
        if (t == 7 and n~= w:GetName()) then  
            SendWorldMessage(string.format("|cFFFF80FF|Hplayer:%s|h[%s]|h悄悄的说:%s|r",n,n,m)) 
        end 
    end
    
    if (c==0x06E) then 
        local n = p:ReadString() 
        SendWorldMessage(string.format("%s 拒绝了你的邀请.",n)) 
    end
    
    if (c==0x069) then 
        local n = p:ReadString() 
        SendWorldMessage(string.format("%s 拒绝了你的邀请.",n)) 
    end 
end)
