-- reparando el nombre del npc custom de transfiguración
UPDATE `creature_template` SET `name` = 'Warpweaver' WHERE `entry` = '190058'; 

-- reparando el texto del npc de instrucciones de transfiguración
UPDATE `npc_text` SET `text0_0` = 'Transmogrification allows you to change how your items look like without changing the stats of the items.\r\nItems used in transmogrification are no longer refundable, tradeable and are bound to you.\r\nUpdating a menu updates the view and prices.\r\n\r\nNot everything can be transmogrified with eachother.\r\nRestrictions include but are not limited to:\r\nOnly armor and weapons can be transmogrified\r\nGuns, bows and crossbows can be transmogrified with eachother\r\nFishing poles can not be transmogrified\r\nYou must be able to equip both items used in the process.\r\n\r\nTransmogrifications stay on your items as long as you own them.\r\nIf you try to put the item in guild bank or mail it to someone else, the transmogrification is stripped.\r\n\r\nYou can also remove transmogrifications for free at the transmogrifier.' WHERE `ID` = '601083'; 

-- traduciendo texto de instrucciones del npc de transfiguración
DELETE FROM `locales_npc_text` WHERE `ID`='601084';
INSERT INTO `locales_npc_text` (`ID`, `Text0_0_loc6`, `Text0_0_loc7`) VALUES ('601084', 'Puede guardar sus propios conjuntos de transfiguración.\r\n\r\nPara guardar, primero debes transfigurar tus objetos equipados.\r\nLuego, cuando vaya al menú de administración de configuración y vaya a guardar el menú de configuración,\r\nTodos los elementos que ha transfigurado se muestran para que vea lo que está guardando.\r\nSi cree que el conjunto está bien, puede hacer clic para guardar el conjunto y nombrarlo como desee.\r\n\r\nPara usar un conjunto, puede hacer clic en el conjunto guardado en el menú de administración de conjuntos y luego seleccionar usar conjunto.\r\nSi el conjunto tiene una transfiguración para un elemento que ya está transfigurado, la transfiguración anterior se pierde.\r\nTenga en cuenta que se aplican las mismas restricciones de transfiguración cuando se intenta usar un conjunto que en la transfiguración normal.\r\n\r\nPara eliminar un conjunto, puede ir al menú del conjunto y seleccionar eliminar conjunto.', 'Puede guardar sus propios conjuntos de transfiguración.\r\n\r\nPara guardar, primero debes transfigurar tus objetos equipados.\r\nLuego, cuando vaya al menú de administración de configuración y vaya a guardar el menú de configuración,\r\nTodos los elementos que ha transfigurado se muestran para que vea lo que está guardando.\r\nSi cree que el conjunto está bien, puede hacer clic para guardar el conjunto y nombrarlo como desee.\r\n\r\nPara usar un conjunto, puede hacer clic en el conjunto guardado en el menú de administración de conjuntos y luego seleccionar usar conjunto.\r\nSi el conjunto tiene una transfiguración para un elemento que ya está transfigurado, la transfiguración anterior se pierde.\r\nTenga en cuenta que se aplican las mismas restricciones de transfiguración cuando se intenta usar un conjunto que en la transfiguración normal.\r\n\r\nPara eliminar un conjunto, puede ir al menú del conjunto y seleccionar eliminar conjunto.'); 

-- traduciendo texto de instrucciones de conjunto de sets del npc de transfiguración
DELETE FROM `locales_npc_text` WHERE `ID`='601083';
INSERT INTO `locales_npc_text` (`ID`, `Text0_0_loc6`, `Text0_0_loc7`) VALUES ('601083', 'La transfiguración le permite cambiar el aspecto de sus elementos sin cambiar las estadísticas de los elementos.\r\nLos artículos utilizados en la transfiguración ya no son reembolsables, intercambiables y están vinculados a usted.\r\nLa actualización de un menú actualiza la vista y los precios.\r\n\r\nNo todo puede transformarse entre sí.\r\nLas restricciones incluyen, pero no se limitan a:\r\nSolo se pueden transfigurar armaduras y armas.\r\nLas armas, los arcos y las ballestas se pueden transfigurar entre sí.\r\nLas cañas de pescar no se pueden transfigurar\r\nDebe poder equipar ambos elementos utilizados en el proceso.\r\n\r\nLas transfiguraciones permanecen en sus artículos mientras los posea.\r\nSi intentas poner el objeto en el banco del gremio o enviarlo por correo a otra persona, la transfiguración se elimina.\r\n\r\nTambién puedes eliminar las transfiguraciones de forma gratuita en el transfigurador.', 'La transfiguración le permite cambiar el aspecto de sus elementos sin cambiar las estadísticas de los elementos.\r\nLos artículos utilizados en la transfiguración ya no son reembolsables, intercambiables y están vinculados a usted.\r\nLa actualización de un menú actualiza la vista y los precios.\r\n\r\nNo todo puede transformarse entre sí.\r\nLas restricciones incluyen, pero no se limitan a:\r\nSolo se pueden transfigurar armaduras y armas.\r\nLas armas, los arcos y las ballestas se pueden transfigurar entre sí.\r\nLas cañas de pescar no se pueden transfigurar\r\nDebe poder equipar ambos elementos utilizados en el proceso.\r\n\r\nLas transfiguraciones permanecen en sus artículos mientras los posea.\r\nSi intentas poner el objeto en el banco del gremio o enviarlo por correo a otra persona, la transfiguración se elimina.\r\n\r\nTambién puedes eliminar las transfiguraciones de forma gratuita en el transfigurador.'); 
